---
- name: check postfix package are installed
  shell: dpkg -l | grep postfix | grep ii | cut -d " " -f1
  register: init
  when: action == 'Instalar'

- name: ensure postfix packages are installed
  apt: 
    pkg: "{{ item }}"
    state: present 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - postfix
    - postfix-pcre
    - postfix-policyd-spf-python
    - mailutils
    - rsyslog
  when: init|changed and init.stdout != "ii" and action == 'Instalar'

#  Aqui debo hacer los certificados autofirmados temporales
- name: create self-signed certificates
  command: /usr/bin/openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout {{ mailserver_ssl_key_file }} -out {{ mailserver_ssl_cert_file }} -subj "/C=VE/ST=Caracas/L=Caracas/O=CNTI/OU=Proyecto Canaima/CN=victopin0@gmail.com"
  when: action == 'Instalar'

- name: update /etc/postfix/main.cf from template
  template:
    src: main.cf
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify:
  - restart postfix
  when: action == 'Instalar'

- name: update /etc/postfix/master.cf from template
  template:
    src: master.cf
    dest: /etc/postfix/master.cf
    owner: root
    group: root
    mode: 0644
  notify:
  - restart postfix
  when: action == 'Instalar'

- name: check package status postfix
  shell: dpkg -l | grep postfix | cut -d " " -f1
  register: status
  when: action == 'Desintalar'

- name: ensure postfix packages are uninstalled
  apt: 
    pkg: "{{ item }}"
    state: absent
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - postfix
    - postfix-pcre
    - postfix-policyd-spf-python
    - mailutils
    - rsyslog
  when: status|changed and status.stdout != "" and action == 'Desintalar'
