#!/bin/sh

set -e

. /usr/share/debconf/confmodule

db_version 2.0

db_input high kit-servicios/kds_user_pass || true

db_go || true

echo "Creando usuario KDS"
adduser --gecos 'KDS system user' --disabled-password --quiet kds || true
      
db_get kit-servicios/kds_user_pass
      
if [ "$RET" ]; then
    echo "kds:$RET" | chpasswd
fi