#!/bin/sh

set -e

. /usr/share/debconf/confmodule

db_version 2.0

db_input high kit-servicios/kds_user_pass || true

db_go || true

echo "Creando usuario KDS"
adduser --system --shell /bin/bash --gecos 'KDS system user' --group --disabled-password --quiet --home /home/kds kds
      
db_get kit-servicios/kds_user_pass
      
if [ "$RET" ]; then
    echo "kds:$RET" | chpasswd
fi