Document: kit-servicios
Title: Debian kit-servicios Manual
Author: <insert document author here>
Abstract: This manual describes what kit-servicios is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kit-servicios/kit-servicios.sgml.gz

Format: postscript
Files: /usr/share/doc/kit-servicios/kit-servicios.ps.gz

Format: text
Files: /usr/share/doc/kit-servicios/kit-servicios.text.gz

Format: HTML
Index: /usr/share/doc/kit-servicios/html/index.html
Files: /usr/share/doc/kit-servicios/html/*.html
