#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: kit-servicios
# ARCHIVO: postrm
# DESCRIPCIÓN: Revierte los cambios hechos por el paquete en los scripts del
#              mantenedor, de forma tal de asegurarse que el sistema quede
#              como estaba antes de su instalación.
# COPYRIGHT:
#  (C) 2016 Victor Pino <victopin0@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

    . /usr/share/debconf/confmodule
    echo "Eliminando la data de la BD de debconf"
    db_purge

    if [ -L  /etc/init.d/celeryd ] ; then

            echo "Eliminando el enlace simbolico de celeryd init"
            unlink /etc/init.d/celeryd

    fi
    
    if [ -L  /etc/default/celeryd ] ; then

            echo "Eliminando el enlace simbolico de celeryd default" 
            unlink /etc/default/celeryd

    fi

    echo "Eliminamos el usuario de rabbitmq"
    rabbitmqctl delete_user kds

    echo "Eliminamos el vhost"
    rabbitmqctl delete_vhost kds_vhost

	echo "Eliminando el divert de celeryd default"
	dpkg-divert --remove --rename /etc/default/celeryd

    echo "Eliminando el divert de celeryd init.d"
    dpkg-divert --remove --rename /etc/init.d/celeryd
	
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



#DEBHELPER#

exit 0
