#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: kit-servicios
# ARCHIVO: preinst
# DESCRIPCIÓN: Configura el sistema antes de la instalación del paquete.
# COPYRIGHT:
#  (C) 2016 Victor Pino <victopin0@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

case "$1" in
    install|upgrade)

	if [ -e /var/lib/dpkg/info/apache2.list ] || [ -e /var/lib/live/config/apache2 ]; then
		service apache2 stop
	fi

	mkdir -p /etc/kds/diverted/default

    mkdir -p /etc/kds/diverted/init.d

    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
