---

- name: check dovecot package are installed
  shell: dpkg -l | grep dovecot-imapd | cut -d " " -f1
  register: init
  when: action == 'Instalar'

- name: ensure dovecot packages are installed
  apt: 
    pkg: "{{ item }}"
    state: present 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - dovecot-imapd
    - dovecot-pop3d
    - dovecot-common
    - dovecot-antispam
    - dovecot-core
    - dovecot-lmtpd
  when: init|changed and init.stdout == "" and action == 'Instalar'

- name: update /etc/dovecot/conf.d/10-auth.conf from template
  template:
    src: 10-auth.conf
    dest: /etc/dovecot/conf.d/10-auth.conf
    owner: root
    group: root
    mode: 0644
  notify:
  - restart dovecot
  when: action == 'Instalar'

- name: update /etc/dovecot/conf.d/10-mail.conf from template
  template:
    src: 10-mail.conf
    dest: /etc/dovecot/conf.d/10-mail.conf
    owner: root
    group: root
    mode: 0644
  notify:
  - restart dovecot
  when: action == 'Instalar'

- name: check package status dovecot
  shell: dpkg -l | grep dovecot-imapd | cut -d " " -f1 
  register: status
  when: action == 'Desintalar'

- name: ensure dovecot packages are uninstalled
  apt: 
    pkg: "{{ item }}"
    state: absent 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - dovecot-imapd
    - dovecot-pop3d
    - dovecot-common
    - dovecot-antispam
    - dovecot-core
    - dovecot-lmtpd
  when: status|changed and status.stdout != "" and action == 'Desintalar'