---
- name: restart dovecot
  service:
    name: dovecot
    state: restarted

- name: restart tomcat6
  service:
    name: tomcat6
    state: restarted

- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: restart sqlgrey
  service:
    name: sqlgrey
    pattern: /usr/sbin/sqlgrey
    state: restarted

- name: restart opendkim
  service:
    name: opendkim
    state: restarted

# ansible service module doesn't seem to work correctly with clamav
- name: restart clamav
  command: service {{ item }} restart
  with_items:
    - clamav-daemon
    - clamav-milter

- name: restart dspam
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - dspam
    - dspam-milter

- name: restart spamassassin
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - spamassassin
    - spamass-milter

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart mysql
  service:
    name: mysql
    state: restarted

- name: restart apache2
  service:
    name: apache2
    state: restarted

- name: import roundcube database
  mysql_db:
    name: roundcube
    target: /usr/share/dbconfig-common/data/roundcube/install/mysql
    state: import

- name: regenerate /etc/roundcube/debian-db.php
  command: dbconfig-generate-include -f php -O root:www-data -m 0640 /etc/dbconfig-common/roundcube.conf /etc/roundcube/debian-db.php