---
- name: check postfix package are installed
  shell: dpkg -l | grep squirrelmail | grep ii | cut -d " " -f1
  register: init
  when: action == 'Instalar'

- name: ensure squirrelmail packages are installed
  apt: 
    pkg: "{{ item }}"
    state: present 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - squirrelmail
    - apache2
    - libapache2-mod-php5
  when: init|changed and init.stdout != "ii" and action == 'Instalar'

- name: update /etc/squirrelmail/config.php from template
  template:
    src: config.php
    dest: /etc/squirrelmail/config.php
    owner: root
    group: www-data
    mode: 0640
  when: action == 'Instalar'

- name: create symlink /usr/share/squirrelmail to /var/www/html/
  command: ln -s /usr/share/squirrelmail/ /var/www/html/
  when: action == 'Instalar'

- name: delete symlink /var/www/html/squirrelmail
  command: unlink /var/www/html/squirrelmail
  when: action == 'Desintalar'
  
#- name: create symlink /usr/share/squirrelmail to /var/www/html/
#  file:
#    src: /usr/share/squirrelmail/ 
#    path: /var/www/html/
#    force: yes
#    state: link
#  notify:
#  - restart apache2

- name: create directory for users in /home/usuarios
  file: 
    path: /home/usuarios
    state: directory
  when: action == 'Instalar'

- name: Changed permission to /var/spool/mail/
  file: 
    path: /var/spool/mail/
    owner: postfix 
    group: postfix 
    mode: 0777
  when: action == 'Instalar'

- name: all privileges for user of postfix
  command: chown postfix:postfix /var/spool/mail
  when: action == 'Instalar'

- name: permission 777 to the directory /var/spool/mail
  command: chmod -R 777 /var/spool/mail
  when: action == 'Instalar'

- name: Add user to the correo
  command: useradd -m -d /home/usuarios/{{user}} {{user}}
  when: action == 'Actualizar'

- name: Add usermod /bin/user
  shell: usermod -s /bin/{{user}} {{user}} && echo "{{ user }}:{{ passwd }}" | sudo chpasswd  
  when: action == 'Actualizar'

- name: ensure all apache services are started
  service:
    name: "{{ item.name }}"
    pattern: "{{ item.pattern }}"
    state: started
  with_items:
    - { name: apache2, pattern: /etc/init.d/apache2 }
  when: action == 'Instalar'

- name: ensure all services are restarted
  service:
    name: "{{ item.name }}"
    pattern: "{{ item.pattern }}"
    state: restarted
  with_items:
    - { name: apache2, pattern: /etc/init.d/apache2 }
    - { name: dovecot, pattern: /etc/init.d/dovecot }
    - { name: postfix, pattern: /etc/init.d/postfix }
  when: action == 'Consultar'

- name: check package status squirrelmail
  shell: dpkg -l | grep squirrelmail | cut -d " " -f1
  register: status
  when: action == 'Desintalar'

- name: ensure squirrelmail packages are uninstalled
  apt: 
    pkg: "{{ item }}"
    state: absent 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - squirrelmail
  when: status|changed and status.stdout != "" and action == 'Desintalar'

