---
- name: ensure roundcube packages are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - squirrelmail
    - squirrelmail-locales
    - locales-all
    - apache2

- name: update /etc/squirrelmail/config.php from template
  template:
    src: config.php
    dest: /etc/squirrelmail/config.php
    owner: root
    group: www-data
    mode: 0640

- name: ensure /etc/squirrelmail/apache.conf exists and links to /etc/apache2/conf-enabled/squirrelmail.conf
  file:
    path: /etc/apache2/conf-enabled/squirrelmail.conf
    src: /etc/squirrelmail/apache.conf
    force: yes
    state: link

- name: ensure all apache services are started
  service:
    name: "{{ item.name }}"
    pattern: "{{ item.pattern }}"
    state: started
  with_items:
    - { name: apache2, pattern: /etc/init.d/apache2 }